# Python para Economistas: Cuarta Clase

#### 1. Actualizando Variables

    En algunos casos sencillos queremos actualizar una variable, por ejemplo sumandole o restandole un valor a la variable original.
<img src="https://latex.codecogs.com/gif.latex?i_1&space;=&space;i_0&space;&plus;&space;1" title="i_1 = i_0 + 1" />


    Esto lo hacemos cuando el valor de la iteración pasada i_0 no es de interés para el programador y simplemente se sobre escribe agregandole el valor que actualiza la variable. Esto ocurre frecuente por ejemplo cuando queremos que "i" rastree el numero de iteraciones que esta realizando un bucle.

In [7]:
ii = 0
print('First value of i:', ii)
ii += 1
print('Second value of i:', ii)
ii -= 1
print('Third value of i:', ii)

k = 5
ii = ii + k 
print('Fourth value of i:', ii)


First value of i: 0
Second value of i: 1
Third value of i: 0
Fourth value of i: 5


#### 2. Loops definidos usando for
    Un bucle "for" se usa para iterar sobre una secuencia (que puede ser una lista, una tupla, un diccionario o un conjunto). Esto se ejecuta con el comando  for. Con el bucle for podemos ejecutar un conjunto de declaraciones, una vez para cada elemento de una lista, tupla, conjunto, etc.

In [11]:
for ii in range(10):
    print(ii)
    print(-ii)
    
print("Final del bucle")

0
0
1
-1
2
-2
3
-3
4
-4
5
-5
6
-6
7
-7
8
-8
9
-9
Final del bucle


In [16]:
for ii in range(1,11):
    strNumber = "Numero: " + str(ii)
    print(strNumber)

Numero: 1
Numero: 2
Numero: 3
Numero: 4
Numero: 5
Numero: 6
Numero: 7
Numero: 8
Numero: 9
Numero: 10


In [17]:
# Se puede iterar a traves de listas
numberList = [1,2,3,4,5]
for ii in numberList:
    print(ii)

1
2
3
4
5


In [18]:
# Se puede iterar a traves de tuplas
numberTuple = (1,2,3,4,5)
for ii in numberTuple:
    print(ii)

1
2
3
4
5


In [19]:
listaDeNumeros = []
for ii in range(1,6):
    newVariable = "Numero: " + str(ii)
    listaDeNumeros.append(newVariable)

print(listaDeNumeros)

['Numero: 1', 'Numero: 2', 'Numero: 3', 'Numero: 4', 'Numero: 5']


#### 3. List comprehension
    Los list comprehension son una version más elegante y menos tediosa de cómo armar listas usando bucles. Esto sirve para ahorrarse lineas y hacer más entendible el código.

In [22]:
# Separamos las letras del string ´Infox´:

# Método 1:

listaLetras = []
for letra in "Infox":
    listaLetras.append(letra)

print("Método 1:", listaLetras)


# Método 2: 
listaLetras = [letra for letra in "Infox"]
print("Método 2:",listaLetras)

Método 1: ['I', 'n', 'f', 'o', 'x']
Método 2: ['I', 'n', 'f', 'o', 'x']


#### 4. Iteraciones con condicionales
    Hay casos en los que queremos omitir una iteración o queremos realizar alguna ejecución distinta cuando alguna condición dentro del bucle no ocurre. En este caso podemos incluir condicionales en las iteraciones.

In [24]:
listaNombres = ['Hector', 'Miguel', 'Christian','Daniela', 'Roxana', 'Ana', 'Claudia', 'Jose', 'Kevin', 'Julieta']

nuevaListaNombres = []

for nombre in listaNombres:
    if nombre[-1] == 'a':
        nuevaListaNombres.append("Trabajadora: " + str(nombre))
    else:
        nuevaListaNombres.append("Trabajador: " + str(nombre))

nuevaListaNombres

['Trabajador: Hector',
 'Trabajador: Miguel',
 'Trabajador: Christian',
 'Trabajadora: Daniela',
 'Trabajadora: Roxana',
 'Trabajadora: Ana',
 'Trabajadora: Claudia',
 'Trabajador: Jose',
 'Trabajador: Kevin',
 'Trabajadora: Julieta']

In [26]:
codigoTrabajador = list(range(1,15))
codigoTrabajadorPar = []

for ii in codigoTrabajador:
    if ii%2 == 0:
        codigoTrabajadorPar.append("Trabajador: "+ str(ii))

codigoTrabajadorPar

['Trabajador: 2',
 'Trabajador: 4',
 'Trabajador: 6',
 'Trabajador: 8',
 'Trabajador: 10',
 'Trabajador: 12',
 'Trabajador: 14']

In [27]:
codigoTrabajadorMultiploSeis = []
for ii in codigoTrabajador:
    if ii%2 == 0 and ii%3 == 0:
        codigoTrabajadorMultiploSeis.append("Trabajador: "+ str(ii))

codigoTrabajadorMultiploSeis

['Trabajador: 6', 'Trabajador: 12']

In [28]:
codigoTrabajadorMultiplos = []
for ii in codigoTrabajador:
    if ii%2 == 0 or ii%3 == 0:
        codigoTrabajadorMultiplos.append("Trabajador: "+ str(ii))

codigoTrabajadorMultiplos

['Trabajador: 2',
 'Trabajador: 3',
 'Trabajador: 4',
 'Trabajador: 6',
 'Trabajador: 8',
 'Trabajador: 9',
 'Trabajador: 10',
 'Trabajador: 12',
 'Trabajador: 14']

#### 5. Nested Iterations
    
    En algunos casos, querremos iterar en múltiples listas, o cuando trabajemos con matrices, múltiples dimensiones. Para esto podemos anidar bucles dentro de otros bucles.

In [31]:
# Nested iteration:
import numpy as np
import copy

zeroArray = np.zeros((5,5))
onesArray = copy.copy(zeroArray)

for ii in range(onesArray.shape[0]):
    for jj in range(onesArray.shape[1]):
        onesArray[ii,jj] = 1

onesArrayDiag = copy.copy(zeroArray)
for ii in range(onesArrayDiag.shape[0]):
    for jj in range(onesArrayDiag.shape[1]):
        if ii == jj:
            onesArrayDiag[ii,jj] = 1
        
print(zeroArray, '\n \n', onesArray, '\n \n', onesArrayDiag)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 
 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 6. Iteraciones en paralelo
    Es común utilizar iteraciones en paralelo cuando queremos iterar a traves de listas diferentes de forma simultanea. Para ello se utiliza el comando zip. Este proceso se puede realizar con el comando zip en el cual se incluye como insumo todas las listas o secuencias a traves de las cuales queremos iterar.

In [34]:
import random

workersNumber = ["Trabajador: " + str(i) for i in range(1,11)]
workersAge  = [random.randint(18, 50) for i in range(10)]
workerRandomNumber = [random.uniform(0, 1) for i in range(10)]


print('Worker Number', '|', 'Age' , '|' , 'Random Number')
print('------------------------------------')

for number, age, randomNumber in zip(workersNumber, workersAge, workerRandomNumber):
    print(number, '|', age , '|' , round(randomNumber,4))


Worker Number | Age | Random Number
------------------------------------
Trabajador: 1 | 44 | 0.7311
Trabajador: 2 | 20 | 0.6178
Trabajador: 3 | 45 | 0.5898
Trabajador: 4 | 49 | 0.1847
Trabajador: 5 | 34 | 0.1559
Trabajador: 6 | 45 | 0.3823
Trabajador: 7 | 28 | 0.6781
Trabajador: 8 | 19 | 0.7535
Trabajador: 9 | 33 | 0.2878
Trabajador: 10 | 34 | 0.2221


In [37]:
groupPeru = []
groupChile = []
groupArgentina = []
groupColombia = []

for randomNumber, number in zip(workerRandomNumber, workersNumber):
    if randomNumber < 0.20:
        groupPeru.append(number)
    elif randomNumber >= 0.20 and randomNumber < 0.30:
        groupChile.append(number)
    elif randomNumber >= 0.30 and randomNumber < 0.60:
        groupArgentina.append(number)
    else:
        groupColombia.append(number)

print('Peru:', groupPeru)
print('Chile:', groupChile)
print('Argentina:', groupArgentina)
print('Colombia:', groupColombia)

Peru: ['Trabajador: 4', 'Trabajador: 5']
Chile: ['Trabajador: 9', 'Trabajador: 10']
Argentina: ['Trabajador: 3', 'Trabajador: 6']
Colombia: ['Trabajador: 1', 'Trabajador: 2', 'Trabajador: 7', 'Trabajador: 8']


In [39]:
def groupAsignment(seed):
    
    if seed < 0.20:
        groupName = "Peru"
    elif seed >= 0.20 and seed < 0.30:
        groupName = "Chile"
    elif seed >= 0.30 and seed < 0.60:
        groupName = "Argentina"
    else:
        groupName = "Colombia"

    return groupName


groupPeru = [number for seed, number in zip(workerRandomNumber, workersNumber) if groupAsignment(seed) == "Peru"]
groupChile = [number for seed, number in zip(workerRandomNumber, workersNumber) if groupAsignment(seed) == "Chile"]
groupArgentina = [number for seed, number in zip(workerRandomNumber, workersNumber) if groupAsignment(seed) == "Argentina"]
groupColombia = [number for seed, number in zip(workerRandomNumber, workersNumber) if groupAsignment(seed) == "Colombia"]

print('Peru:', groupPeru)
print('Chile:', groupChile)
print('Argentina:', groupArgentina)
print('Colombia:', groupColombia)

Peru: ['Trabajador: 4', 'Trabajador: 5']
Chile: ['Trabajador: 9', 'Trabajador: 10']
Argentina: ['Trabajador: 3', 'Trabajador: 6']
Colombia: ['Trabajador: 1', 'Trabajador: 2', 'Trabajador: 7', 'Trabajador: 8']


#### 7. While Statements:
    Con el comando while podemos ejecutar un conjunto de declaraciones siempre y cuando la condición inicial con que se ejecuta el comando while sea verdadera. Lo ideal es que esta condición sea modificada o cambie endogenamente en base a lo que ocurre dentro del bucle.



In [43]:
jj = 0
while jj <= 100:
    jj = jj + 1
    if jj%10 == 0:
        print("Estamos en el numero: " + str(jj))
        
print(jj)

Estamos en el numero: 10
Estamos en el numero: 20
Estamos en el numero: 30
Estamos en el numero: 40
Estamos en el numero: 50
Estamos en el numero: 60
Estamos en el numero: 70
Estamos en el numero: 80
Estamos en el numero: 90
Estamos en el numero: 100
101
